export const ADD_SERVICE = 'ADD_SERVICE';
export const REMOVE_SERVICE = 'REMOVE_SERVICE';
export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
export const FILL_SERVICE_FIELD = 'FILL_SERVICE_FIELD';
export const FILTER_SERVICE_LIST = 'FILTER_SERVICE_LIST';